services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APPDATA}/sonarr:/config
      - ${TV}:/tv
      - ${ANIME}:/anime
      - ${DOWNLOADS}:/downloads
      - ${MEDIA_ROOT}:/mnt

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APPDATA}/radarr:/config
      - ${MOVIES}:/movies
      - ${ANIME}:/anime
      - ${DOWNLOADS}:/downloads
      - ${MEDIA_ROOT}:/mnt

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APPDATA}/prowlarr:/config

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
      - 8920:8920 # for HTTPS
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APPDATA}/jellyfin:/config
      - ${MEDIA_ROOT}:/mnt
    devices:
      # OPTIONAL – only if you want hardware transcoding (Intel iGPU)
      - /dev/dri:/dev/dri

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    ports:
      - 6767:6767
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APPDATA}/bazarr:/config
      - ${TV}:/tv
      - ${MOVIES}:/movies
      - ${ANIME}:/anime
      - ${DOWNLOADS}:/downloads
      - ${MEDIA_ROOT}:/mnt

  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APPDATA}/kavita:/config
      - ${COMICS}:/comics
      - ${MANGA}:/manga
      - ${BOOKS}:/books
    ports:
      - "5000:5000"
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    init: true
    restart: unless-stopped
    ports:
      - 5055:5055
    environment:
      - LOG_LEVEL = info
      - TZ = ${TZ}
      - PUID = ${PUID}
      - PGID = ${PGID}
      - PORT = 5055
    volumes:
      - ${APPDATA}/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

networks:
  default:
    driver: bridge
